### ISSUE TITLE
Can we move bootstrappers included in skeleton app to modules?

### ISSUE THREAD

**Issue by davidbyoung** [aphiria/aphiria#15]
# Goal

* Remove framework-specific bootstrappers from userland so that their apps' don't have too much framework-specific code/bootstrappers mixed in with app-specific code/bootstrappers
  * This makes it more similar to ASP.NET Core - you don't need to explicitly bootstrap it, but you do have entry points to customize the bootstrapping of the framework
* Move [app bootstrappers](https://github.com/aphiria/app/tree/master/src/Api/Bootstrappers) to Aphiria's source control

# Difficulties

* How do we make it simple to configure things that are currently in those bootstrappers, eg paths to cache files, supported languages, etc?

**Comment by davidbyoung** [comment]
One idea for allowing configuration of framework components would be to use a YAML config file.  The settings here would be global to all environments (which differentiates it from `.env` files)

```yaml
console:
  annotationPaths:
    - src
  commandCache: tmp/framework/console/commandCache.txt
  useAnnotations: true

contentNegotiation:
  encodingMatcher: \Aphiria\Net\Http\ContentNegotiation\AcceptCharsetEncodingMatcher
  languageMatcher: \Aphiria\Net\Http\ContentNegotiation\AcceptLanguageMatcher
  mediaTypeFormatters:
    - \Aphiria\Net\Http\ContentNegotiation\MediaTypeFormatters\JsonMediaTypeFormatter
    - \Aphiria\Net\Http\ContentNegotiation\MediaTypeFormatters\FormUrlEncodedMediaTypeFormatter
    - \Aphiria\Net\Http\ContentNegotiation\MediaTypeFormatters\HtmlMediaTypeFormatter
    - \Aphiria\Net\Http\ContentNegotiation\MediaTypeFormatters\PlainTextMediaTypeFormatter
  supportedLanguages:
    - en-US

exceptions:
  errorLogLevels: 0
  errorThrownLevels: 8191 # (E_ALL & ~(E_DEPRECATED | E_USER_DEPRECATED))
  exceptionLogLevels:
    - error
    - critical
    - alert
    - emergency
  useProblemDetails: true

logging:
  handler:
    stream:
      path: tmp/logs/errors.txt
  name: app

routing:
  annotationPaths:
    - src
  routeCache: tmp/framework/http/routeCache.txt
  trieCache: tmp/framework/http/trieCache.txt
  useAnnotations: true

serialization:
  dateFormat: atom
  propertyNameFormatter: \Aphiria\Serialization\Encoding\CamelCasePropertyNameFormatter

validation:
  annotationPaths:
    - src
  useAnnotations: true
```

This would require some switch statements for things like `dateFormat: atom` so that we know how to parse the value.
